plan_trip:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: wiener_linien_austria
    origin:
      required: false
      example: Stephansplatz
      selector:
        text:
    destination:
      required: false
      example: Westbahnhof
      selector:
        text:
    arrive_by:
      required: true
      default: false
      selector:
        boolean:
    datetime:
      required: false
      selector:
        datetime:
